server:
  port: 9000

logging:
  level:
    org.springframework.security: trace
    
spring:
  security:
    user:
      name: alefe
      password: 123
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "client"
              client-secret: "secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "read"
                - "openid"
                - "profile"
            require-authorization-consent: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 
